<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-09-15 16:18

$extensionPath = t3lib_extMgm::extPath('ren_veille_documentaire');
return array(
	'tx_renveilledocumentaire_tceforms_suggest_keywordsreceiver' => $extensionPath . 'class.tx_renveilledocumentaire_tceforms_suggest_keywordsreceiver.php',
	'tx_renveilledocumentaire_renderer' => $extensionPath . 'mod1/class.tx_renveilledocumentaire_renderer.php',
	'tx_renveilledocumentaire_module1' => $extensionPath . 'mod1/index.php',
	'tx_renveilledocumentaire_pi1' => $extensionPath . 'pi1/class.tx_renveilledocumentaire_pi1.php',
	'tx_renveilledocumentaire_pi1_wizicon' => $extensionPath . 'pi1/class.tx_renveilledocumentaire_pi1_wizicon.php',
	'tx_renveilledocumentaire_pi2' => $extensionPath . 'pi2/class.tx_renveilledocumentaire_pi2.php',
	'tx_renveilledocumentaire_pi2_wizicon' => $extensionPath . 'pi2/class.tx_renveilledocumentaire_pi2_wizicon.php',
	'tx_renveilledocumentaire_relations' => $extensionPath . 'class.tx_renveilledocumentaire_relations.php',
);
?>